set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_C_FLAGS "/Z7 /Gy")
set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")
set(VCPKG_C_FLAGS_RELEASE "/O2 /Ob3 /GT /GL")
set(VCPKG_CXX_FLAGS_RELEASE "${VCPKG_C_FLAGS_RELEASE}")
set(VCPKG_LINKER_FLAGS "/OPT:REF /OPT:ICF /PDBALTPATH:\%_PDB\%")
